// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK-M_geB9VmbK9WLHhQra7yR2m6GiRdmE',
    appId: '1:274614819324:web:4fa714fabcc7242541fa79',
    messagingSenderId: '274614819324',
    projectId: 'moodsic-97119',
    authDomain: 'moodsic-97119.firebaseapp.com',
    storageBucket: 'moodsic-97119.appspot.com',
    measurementId: 'G-G520YTMNXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu5OrppR17a72auWC09GjE-gBzsEGZ1ak',
    appId: '1:274614819324:android:2824bfa30184e34b41fa79',
    messagingSenderId: '274614819324',
    projectId: 'moodsic-97119',
    storageBucket: 'moodsic-97119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcaKA6XlK6c71uHkHD7iLwDw2VZiMRmLA',
    appId: '1:274614819324:ios:fef5f3a1032fd7c941fa79',
    messagingSenderId: '274614819324',
    projectId: 'moodsic-97119',
    storageBucket: 'moodsic-97119.appspot.com',
    iosBundleId: 'com.example.moodsic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcaKA6XlK6c71uHkHD7iLwDw2VZiMRmLA',
    appId: '1:274614819324:ios:2f5aa8a11254016541fa79',
    messagingSenderId: '274614819324',
    projectId: 'moodsic-97119',
    storageBucket: 'moodsic-97119.appspot.com',
    iosBundleId: 'com.example.moodsic.RunnerTests',
  );
}
